"""Add user_id to Comments

Revision ID: 6033874ca42f
Revises: 
Create Date: 2025-11-14 12:53:55.045672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6033874ca42f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=50), nullable=False))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
